#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys, math

me = 'cligraph'

# don't draw bars longer than this
maxcol = 60
if len(sys.argv) == 2:
    maxcol = int(sys.argv[1])

# divide the input numbers by this
scale = 1
if len(sys.argv) == 3:
    scale = float(sys.argv[2])

x = float(sys.stdin.readline().rstrip())

# only 1 cligraph instance per server. i don't need more
spool = open("/run/shm/"+me,"ar+")

try:

    xprev = float(spool.readline().rstrip())

except ValueError:
    xprev = x

#non-negative derivative
dx = abs(x-xprev)

lenght = int(dx/scale)

mark = ' '
if lenght > maxcol:
    lenght = maxcol
    mark = 'X'

lbar = "*"*lenght
rbar = " "*(maxcol-lenght)
graph = "dx"+lbar+mark+rbar+" "

print (graph+"=%.2f,  x=%.2f, scale=%.2f") % (dx, x, scale)

# update the accumulator
spool.seek(0)
spool.truncate()
spool.write(str(x))

spool.close()







     
